Repository arfc/moltres, pull requests merged in 2020-10, with the labels that each got.

#120 Fix extractSerpent2GCs.py and moltres_xs.py, and add tests
  include/kernels/CoupledFissionEigenKernel.h
  include/kernels/CoupledFissionKernel.h
  include/materials/GraphiteTwoGrpXSFunctionMaterial.h
  include/materials/MsreFuelTwoGrpXSFunctionMaterial.h
  include/materials/NuclearMaterial.h
  property_file_dir/serp3d2group0.78eV/2g0.78eV_fuel_CHID.txt
  property_file_dir/serp3d2group0.78eV/2g0.78eV_fuel_CHIP.txt
  property_file_dir/serp3d2group0.78eV/2g0.78eV_moder_CHID.txt
  property_file_dir/serp3d2group0.78eV/2g0.78eV_moder_CHIP.txt
  python/extractSerpent2GCs.py
  python/moltres_xs.py
  python/test/MSFR_base.coe
  python/test/MSFR_base_res.m
  python/test/gold/PinXS.json
  python/test/gold/xs/msfr_blanket_BETA_EFF.txt
  python/test/gold/xs/msfr_blanket_CHID.txt
  python/test/gold/xs/msfr_blanket_CHIP.txt
  python/test/gold/xs/msfr_blanket_CHIT.txt
  python/test/gold/xs/msfr_blanket_DIFFCOEF.txt
  python/test/gold/xs/msfr_blanket_FISS.txt
  python/test/gold/xs/msfr_blanket_FLX.txt
  python/test/gold/xs/msfr_blanket_INVV.txt
  python/test/gold/xs/msfr_blanket_KAPPA.txt
  python/test/gold/xs/msfr_blanket_LAMBDA.txt
  python/test/gold/xs/msfr_blanket_NSF.txt
  python/test/gold/xs/msfr_blanket_NUBAR.txt
  python/test/gold/xs/msfr_blanket_REMXS.txt
  python/test/gold/xs/msfr_blanket_SP0.txt
  python/test/gold/xs/msfr_fuel_BETA_EFF.txt
  python/test/gold/xs/msfr_fuel_CHID.txt
  python/test/gold/xs/msfr_fuel_CHIP.txt
  python/test/gold/xs/msfr_fuel_CHIT.txt
  python/test/gold/xs/msfr_fuel_DIFFCOEF.txt
  python/test/gold/xs/msfr_fuel_FISS.txt
  python/test/gold/xs/msfr_fuel_FLX.txt
  python/test/gold/xs/msfr_fuel_INVV.txt
  python/test/gold/xs/msfr_fuel_KAPPA.txt
  python/test/gold/xs/msfr_fuel_LAMBDA.txt
  python/test/gold/xs/msfr_fuel_NSF.txt
  python/test/gold/xs/msfr_fuel_NUBAR.txt
  python/test/gold/xs/msfr_fuel_REMXS.txt
  python/test/gold/xs/msfr_fuel_SP0.txt
  python/test/msfr_xs.inp
  python/test/pin.t16
  python/test/pin_cell_XS.inp
  python/test/test_extractSerpent2GCs.py
  python/test/test_moltres_xs.py
  src/kernels/CoupledFissionEigenKernel.C
  src/kernels/CoupledFissionKernel.C
  src/materials/GenericMoltresMaterial.C
  src/materials/GraphiteTwoGrpXSFunctionMaterial.C
  src/materials/MoltresJsonMaterial.C
  src/materials/MsreFuelTwoGrpXSFunctionMaterial.C
  src/materials/NuclearMaterial.C
  src/materials/RoddedMaterial.C
  tutorial/step01_groupConstants/MSREProperties/msre_gentry_4g_fuel_rod0_CHIP.txt
  tutorial/step01_groupConstants/MSREProperties/msre_gentry_4g_moder_rod0_CHIP.txt
Labels: Comp:Core, Difficulty:2-Challenging, Priority:1-Critical, Status:5-In Review, Type:Bug, Type:Test

#125 Update to new MOOSE JSON package
  .gitignore
  include/materials/MoltresJsonMaterial.h
  src/materials/MoltresJsonMaterial.C
Labels: Comp:Input, Difficulty:2-Challenging, Priority:2-Normal, Status:5-In Review, Type:Feature

#134 Update broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Difficulty:1-Beginner, Priority:3-Desired, Status:1-New, Type:Bug, Type:Docs
