Repository arfc/moltres, pull requests merged in 2025-02, with the labels that each got.

#300 Update gh pages action
  .github/workflows/auto-update-gh-pages.yml
Labels: Comp:Build, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Docs

#301 Direct questions to github issues not discussions page which no one uses.
  README.md
Labels: Comp:Core, Difficulty:1-Beginner, Priority:3-Desired, Status:5-In Review, Type:Docs

#302 Include more of what we use
  src/bcs/CoupledScalarAdvectionNoBCBC.C
  src/bcs/ScalarAdvectionArtDiffNoBCBC.C
  src/kernels/CoupledScalarAdvection.C
  src/kernels/DivFreeCoupledScalarAdvection.C
  src/kernels/ScalarAdvectionArtDiff.C
Labels: Comp:Core, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Bug
